clinica/applications/home/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'home_app'

urlpatterns = [
    path(
        '', 
        views.InicioView.as_view(), 
        name='inicio'
    ),
    path(
        'contacto-form', 
        views.FormularioCreateView.as_view(), 
        name='contacto'
    ),
    path(
        'Horario-ubicacion', 
        views.HorariosUbicacionView.as_view(), 
        name='horarioUbicacion'
    ),
    path(
        'clínica', 
        views.ClinicaView.as_view(), 
        name='clinica'
    ),
    path(
        'Antes-Despues', 
        views.AntesDespues.as_view(), 
        name='antesdespues'
    ),
    path(
        'dtecnologias/<pk>/', 
        views.TecnosDetailView.as_view(), 
        name='tecnologias-detail'
    ),
    path(
        'tecnologias', 
        views.TecnosListView.as_view(), 
        name='tecnos-list'
    ),
    path(
        'dservicios/<pk>/', 
        views.ServiceDetailView.as_view(), 
        name='service-detail'
    ),
    path(
        'servicios', 
        views.ServListView.as_view(), 
        name='servicios-list'
    ),
]

clinica/clinica/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
#from applications.home.models import datos
from django.conf.urls import handler404, handler500
from applications.home.views import Error404view, Error405view


urlpatterns = [
    path('admin/', admin.site.urls, {'extra_context': {'mycontext': ''}}),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('applications.home.urls')),
    path('', include('applications.empresa.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = Error404view.as_view()
handler500 = Error405view.as_view()

clinica/templates/includes/footer.html
<footer class="footerjose d-flex flex-column" style="width: 100%; height: auto; background-color: #f2f2f2; border-top: 2px solid whitesmoke;">
  <div class="d-flex w-100 flex-lg-row justify-content-around flex-column align-items-center" style="padding-top: 1rem; padding-bottom: 1rem;">
    <div class="logojose w-10">
      {% if inicio %}
      <a href=""><img style="height: 50px;" src="{{ inicio.logo.url }}" alt=""></a>
      {% endif %}
    </div>
    {% if info %}
    <div class="d-flex flex-lg-row justify-content-between flex-column align-items-center" style="padding: 1rem 0 1rem 0;">
      <div class="p-lg-2 py-md-1">
        <p class="m-0"><i class="fa fa-envelope-o" aria-hidden="true"></i> {{ info.gmail }}</p>
      </div>
      <div class="p-lg-2">
        <p class="m-0"><i class="fa fa-phone" aria-hidden="true"></i> {{ info.phome }}</p>
      </div>
      <div class="p-lg-2">
        <p class="m-0"><i class="fa fa-map-marker" aria-hidden="true"></i> {{ info.address }} - {{ info.district }}</p>
      </div>
    </div>

    <div class="d-flex align-items-center">
      {% for co in info.redes.all %}
      {% if 'facebook.com' in co.url %}
      <a href="{{ co.url }}" target="_blank"><i class="fa fa-facebook-official" aria-hidden="true" style="font-size: 1.5em;"></i></a>
      {% endif %}
      {% if 'instagram.com' in co.url %}
      <a href="{{ co.url }}" target="_blank"><i class="fa-brands fa-square-instagram" style="font-size: 1.5em;"></i></a>
      {% endif %}
      {% if 'linkedin.com' in co.url %}
      <a href="{{ co.url }}" target="_blank"><i class="fa fa-linkedin" style="font-size: 1.5em; color:rgb(0, 140, 255);"></i></a>
      {% endif %}
      {% if 'youtube.com' in co.url %}
      <a href="{{ co.url }}" target="_blank"><i class="fa-brands fa-youtube" style="font-size: 1.5em; color: red;"></i></a>
      {% endif %}
      {% if 'tiktok.com' in co.url %}
      <a href="{{ co.url }}" target="_blank"><i class="fa-brands fa-tiktok" style="font-size: 1.5em;"></i></a>
      {% endif %}
      {% if 'pinterest.com' in co.url %}
      <a href="{{ co.url }}" target="_blank"><i class="fa-brands fa-pinterest" style="font-size: 1.5em; color: red"></i></a>
      {% endif %}
      {% if 'twitter.com' in co.url %}
      <a href="{{ co.url }}" target="_blank"><i class="fa-brands fa-twitter" style="font-size: 1.5em; color: rgb(72, 129, 235)"></i></a>
      {% endif %}
      {% endfor %}
    </div>
    {% endif %}
  </div>

  <div class="copyright w-100 m-0 p-0" style="background-color: #335a80; height: 10%;">
    <div class="copyright-list clearfix d-flex flex-lg-row justify-content-evenly m-0 flex-column align-items-center">
      <div>
        <p>@Todos los Derechos Reservados 2023 - Lima, Perú </p>
      </div>
      <div>
        <p>Aviso de Privacidad</p>
      </div>
      <div>
        <p>Desarrollado por <a href="" target="_blank" rel="inicdoer">Inicoder</a></p>
      </div>
      
      
      
    </div>
  </div>
</footer>

clinica/templates/includes/header.html
<div class="copyright w-100 m-0 p-0" style="background-color: rgb(2, 32, 95); height: 10%;" id="headertop">
  <div class="w-100 copyright-list clearfix row">
    <div class="col-4 d-flex justify-content-center flex-lg-row flex-column align-items-center">
      <i class="fa fa-envelope-o" aria-hidden="true"></i>
      <p> {{ info.gmail }}</p>
    </div>
    <div class="col-4 d-flex justify-content-center flex-lg-row flex-column align-items-center">
      <i class="fa fa-phone mr-1" aria-hidden="true"></i>
      <p> {{ info.phome }}</p>
    </div>
    <div class="col-4 d-flex justify-content-center flex-lg-row flex-column align-items-center">
      <i class="fa fa-map-marker mr-1" aria-hidden="true"></i>
      <p> {{ info.address }}-{{ info.district }}</p>
    </div>
  </div>
</div>
<nav class="navjose" style="min-height: auto">
  <div id="logotrue">
    {% if inicio %}
    <div class="imgjose">
      <a href=""><img class="logo-empresa" src="{{ inicio.logo.url }}" alt="{{ inicio.title }}"></a>   
    </div>
    {% endif %}
    <div class="menu-jose" id="toggle-Button">
      <div class="menu-line-jose"></div>
      <div class="menu-line-jose"></div>
      <div class="menu-line-jose"></div>
    </div>
  </div>
  
  <ul class="list-jose active" id="jose-list">
    <li class="list_hijo"><a href="{% url 'home_app:inicio' %}">INICIO</a></li>

    {% if clinica.public == True %}
    <li class="list_hijo"><a href="{% url 'home_app:clinica' %}">CLÍNICA</a></li>
    {% endif %}

    {% if serv.public %}
    <li class="list_hijo"><a href="{% url 'home_app:servicios-list' %}">SERVICIOS</a></li>
    {% endif %}

    {% if tec.public %}
    <li class="list_hijo"><a href="{% url 'home_app:tecnos-list' %}">TECNOLOGÍAS</a></li>
    {% endif %}
    
    {% if ayd.public %}
    <li class="list_hijo"><a href="{% url 'home_app:antesdespues' %}">ANTES/DESPUES</a></li>
    {% endif %}

    {% if contacto.email %}
    <li class="list_hijo"><a href="{% url 'home_app:contacto' %}">CONTÁCTO</a></li>
    {% endif %}

    {% if horario.public and horario.info %}
    <li class="list_hijo"><a href="{% url 'home_app:horarioUbicacion' %}">HORARIO/UBICACIÓN</a></li>
    {% else %}
      {% if horario.public %}
      <li class="list_hijo"><a href="{% url 'home_app:horarioUbicacion' %}">HORARIO</a></li>
      {% else %}
        {% if horario.info %}
        <li class="list_hijo"><a href="{% url 'home_app:horarioUbicacion' %}">UBICACIÓN</a></li>
        {% endif %}
      {% endif %}
    {% endif %}
  </ul>
  
  <div class="iconos_jose justify-content-between justify-content-center" id="icon_jose">
    {% if contacto.wsp %}
      
          <a type="button" target="_blank" class="btn" href="https://api.whatsapp.com/send?phone=51{% if info %}{{contacto.phome}}{% endif %}&text=Bienvenid@, en que podemos ayudarte? :)" style="color: white;"><i class="fa fa-whatsapp" aria-hidden="true" style="color: white; font-size: 1.5em;"></i> WHATSAPP</a>
          <!-- <a href=""><i class="fa fa-instagram" aria-hidden="true"></i></a> -->
      
    {% endif %}
  </div>

  
</nav>