clinica/applications/empresa/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


app_name = 'empresa_app'

urlpatterns = [
    
    
]

clinica/applications/home/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'home_app'

urlpatterns = [
    path(
        '', 
        views.InicioView.as_view(), 
        name='inicio'
    ),
    path(
        'contacto-form', 
        views.FormularioCreateView.as_view(), 
        name='contacto'
    ),
    path(
        'Horario-ubicacion', 
        views.HorariosUbicacionView.as_view(), 
        name='horarioUbicacion'
    ),
    path(
        'clínica', 
        views.ClinicaView.as_view(), 
        name='clinica'
    ),
    path(
        'Antes-Despues', 
        views.AntesDespues.as_view(), 
        name='antesdespues'
    ),
    path(
        'dtecnologias/<pk>/', 
        views.TecnosDetailView.as_view(), 
        name='tecnologias-detail'
    ),
    path(
        'tecnologias', 
        views.TecnosListView.as_view(), 
        name='tecnos-list'
    ),
    path(
        'dservicios/<pk>/', 
        views.ServiceDetailView.as_view(), 
        name='service-detail'
    ),
    path(
        'servicios', 
        views.ServListView.as_view(), 
        name='servicios-list'
    ),
]

clinica/clinica/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
#from applications.home.models import datos
from django.conf.urls import handler404, handler500
from applications.home.views import Error404view, Error405view


urlpatterns = [
    path('admin/', admin.site.urls, {'extra_context': {'mycontext': ''}}),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('applications.home.urls')),
    path('', include('applications.empresa.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = Error404view.as_view()
handler500 = Error405view.as_view()

clinica/applications/empresa/models.py
# -*- coding: utf-8 -*-
from datetime import datetime
from time import strftime
from django.db import models
from model_utils.models import TimeStampedModel
from ckeditor_uploader.fields import RichTextUploadingField
from .validators import phone_validation, house_validation
from ..home.managers import servicioManager
from applications.complementos.models import Tag, Redes, Especialidad, Categoria
from django.contrib.auth.models import AbstractBaseUser
from PIL import Image
import imagehash
import os

# Create your models here.

def wrapper(instance, filename):
        ext = filename.split('.')[-1]
        hash = imagehash.average_hash(Image.open(instance.image)).__str__()
        
        if hash:
            #Creando nuevo nombre
            filename = '{}.{}'.format(hash, ext) # do instance.username 

        return os.path.join('Tecnologias', filename)

def wrapper2(instance, filename):
        ext = filename.split('.')[-1]
        hash = imagehash.average_hash(Image.open(instance.image)).__str__()
        
        if hash:
            #Creando nuevo nombre
            filename = '{}.{}'.format(hash, ext) # do instance.username 

        return os.path.join('Servicios', filename)

def wrapper3(instance, filename):
        ext = filename.split('.')[-1]
        hash = imagehash.average_hash(Image.open(instance.image)).__str__()
        
        if hash:
            #Creando nuevo nombre
            filename = '{}.{}'.format(hash, ext) # do instance.username 

        return os.path.join('Empleados', filename)

# Informacion

class Informacion(models.Model):
    address = models.CharField('Direccion', max_length=60)
    district = models.CharField('Distrito', max_length=200)
    phome = models.CharField('Numero', validators=[phone_validation], max_length=9, unique=True)
    house = models.CharField('Numero Fijo', validators=[house_validation], max_length=10, unique=True)
    gmail = models.EmailField('Correo')
    redes = models.ManyToManyField(Redes)

    class Meta:
        verbose_name = 'Información'
        verbose_name_plural = 'Información'

    def __str__(self):
        return self.address

# ============================ 

# Tecnologia

class Tecnologia(models.Model):
    title = models.CharField('Nombre', max_length=30, unique=True)
    description = RichTextUploadingField('Descripción')
    image = models.ImageField('Imágen', upload_to=wrapper, blank=False, null=False, default='')
    hash = models.CharField(max_length=20, editable=False)
    public = models.BooleanField('Visible', default=False)

    class Meta:
        verbose_name = 'Tecnologia'
        verbose_name_plural = 'Tecnologias'
        
    def __str__(self):
        return self.title

# ==================================== 

# Horarios y ubicacion

class Horario(models.Model):

    horarios= (
        ('0', 'Lunes'),
        ('1', 'Martes'),
        ('2', 'Miercoles'),
        ('3', 'Jueves'),
        ('4', 'Viernes'),
        ('5', 'Sábado'),
        ('6', 'Domingo'),
    )
    the = models.CharField('De', max_length=11, choices=horarios)
    to = models.CharField('a', max_length=11, choices=horarios, blank=True)
    of = models.TimeField('Desde')
    until = models.TimeField('Hasta')
    public = models.BooleanField('Visible', default=False)

    class Meta:
        verbose_name = 'Horario'
        verbose_name_plural = 'Horarios'

    def __str__(self):
        day = " "
        day2 = " "
        inicio = " "
        final = " "
        for c in self.the:
            if c == '0':
                day = 'Lunes'
            if c == '1':
                day = 'Martes'
            if c == '2':
                day = 'Miercoles'
            if c == '3':
                day = 'Jueves'
            if c == '4':
                day = 'Viernes'
            if c == '5':
                day = 'Sábado'
            if c == '6':
                day = 'Domingo'    
            for d in self.to:
                if d == '0':
                    day2 = 'Lunes'
                if d == '1':
                    day2 = 'Martes'
                if d == '2':
                    day2 = 'Miercoles'
                if d == '3':
                    day2 = 'Jueves'
                if d == '4':
                    day2 = 'Viernes'
                if d == '5':
                    day2 = 'Sábado'
                if d == '6':
                    day2 = 'Domingo'

        a = self.of.strftime("%H:%M")
        b = self.until.strftime("%H:%M")

        if self.of.hour >= 12 and self.of.hour <=24:
            inicio =  a + ' pm'
        else:
            inicio = a + ' am'
        
        if self.until.hour >= 12 and self.until.hour <=24:
            final =  b + ' pm'
        else:
            final = b + ' am'
        
        if day2 == " ":
            return day + ' / ' + 'Desde ' + inicio + ' hasta ' + final
        else:
            return 'De' + ' ' + day + ' a ' + day2 + ' / ' + 'Desde ' + inicio + ' hasta ' + final

# ====================================

# Servicios

class Servicio(TimeStampedModel):
    title = models.CharField('Nombre', max_length=20, unique=True)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE, related_name='s_cate')
    image = models.ImageField('Imagen', upload_to=wrapper2, blank=False, null=False, default='')
    description = RichTextUploadingField('Contenido')
    etiquetas = models.ManyToManyField(Tag)
    public  = models.BooleanField('Visible', default=False)
    slug = models.SlugField(editable=False, max_length=300)

    objects = servicioManager()

    class Meta:
        verbose_name = 'Servicio'
        verbose_name_plural = 'Servicios'
    
    def __str__(self):
        return self.title

# ====================================

#Configuracion 

class Configuration(models.Model):
    tls = models.BooleanField('EMAIL_USE_TLS',default=True, blank=False)
    emailhost = models.CharField('EMAIL_HOST',max_length=1024, default = "smtp.gmail.com", blank=False)
    email = models.EmailField('EMAIL_USER', max_length=255, blank = False)
    password = models.CharField('EMAIL_PASS', max_length=255, blank = False)
    emailport = models.PositiveSmallIntegerField('EMAIL_PORT',default=587, blank=False)

    class Meta:
        verbose_name = 'Configuración'
        verbose_name_plural = 'Configuración'


# Empleado
 
class Empleado(TimeStampedModel):
    name = models.CharField('Nombre', max_length=30)
    last_name = models.CharField('Apellido', max_length=30)
    image = models.ImageField('Foto Perfil', upload_to=wrapper3, blank=False, null=False)
    especialidad = models.ManyToManyField(Especialidad)
    cop = models.CharField('C.O.P', max_length=10)
    public = models.BooleanField('Pestaña Clinica', default=False)
    inicio = models.BooleanField('Pestaña Inicio', default=False)
    
    class Meta:
        verbose_name = 'Empleado'
        verbose_name_plural = 'Empleados'
        ordering = ['name']
        unique_together = ('name', 'last_name')

    def __str__(self):
        return self.name + ' ' + self.last_name

# ==================================== 

clinica/applications/empresa/views.py
from django.shortcuts import render

clinica/templates/empresa/detailServcicio.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Contacto {% endblock title %}
{% block css %}<link rel="stylesheet" href="{% static 'css/SERVICIOS.css' %}" media="screen"> {% endblock css %}
{% block content %}
{% include 'includes/header.html' %}
{% if object %}
<div class="blog-single gray-bg" style="background-image: linear-gradient(rgb(206, 223, 245), rgb(230, 236, 245), #f2f2f2); height: 80%;">
  <div class="container">
      <div class="row align-items-start">
          <div class="col-lg-8 m-15px-tb">
              <article class="article">
                  <div class="article-img" style="height: 20rem;">
                      <img src="{{ object.image.url }}" title="{{ object.title }}" alt="{{ object.title}}" style="object-fit: cover; width: 100%; height: 100%; border-radius: 15px;">
                  </div>
                  <div class="article-title">
                      <!--<h6><a href="#">Lifestyle</a></h6>-->
                      <h2 style="font-family: 'Nunito', sans-serif;">{{ object.title }}</h2>
                      <!--<div class="media">
                          <div class="avatar">
                              <img src="https://bootdey.com/img/Content/avatar/avatar1.png" title="" alt="">
                          </div>
                          <div class="media-body">
                              <label>Rachel Roth</label>
                              <span>26 FEB 2020</span>
                          </div>
                      </div>-->
                  </div>
                  <div class="article-content">
                      {{ object.description|safe }}
                  </div>
                  {% if object.etiquetas %}
                 
                  <div class="nav tag-cloud">
                    {% for e in object.etiquetas.all %}
                      <a style="color: white;">{{ e.name }}</a>
                    {% endfor %}
                  </div>
                  {% endif %}
              </article>
              <!--<div class="contact-form article-comment">
                  <h4>Leave a Reply</h4>
                  <form id="contact-form" method="POST">
                      <div class="row">
                          <div class="col-md-6">
                              <div class="form-group">
                                  <input name="Name" id="name" placeholder="Name *" class="form-control" type="text">
                              </div>
                          </div>
                          <div class="col-md-6">
                              <div class="form-group">
                                  <input name="Email" id="email" placeholder="Email *" class="form-control" type="email">
                              </div>
                          </div>
                          <div class="col-md-12">
                              <div class="form-group">
                                  <textarea name="message" id="message" placeholder="Your message *" rows="4" class="form-control"></textarea>
                              </div>
                          </div>
                          <div class="col-md-12">
                              <div class="send">
                                  <button class="px-btn theme"><span>Submit</span> <i class="arrow"></i></button>
                              </div>
                          </div>
                      </div>
                  </form>
              </div>-->
          </div>
          <div class="col-lg-4 m-15px-tb blog-aside">
              <!-- Author 
              <div class="widget widget-author">
                  <div class="widget-title">
                      <h3>Author</h3>
                  </div>
                  <div class="widget-body">
                      <div class="media align-items-center">
                          <div class="avatar">
                              <img src="https://bootdey.com/img/Content/avatar/avatar6.png" title="" alt="">
                          </div>
                          <div class="media-body">
                              <h6>Hello, I'm<br> Rachel Roth</h6>
                          </div>
                      </div>
                      <p>I design and develop services for customers of all sizes, specializing in creating stylish, modern websites, web services and online stores</p>
                  </div>
              </div>
              End Author -->
              <!-- Trending Post -->
              <!--<div class="widget widget-post">
                  <div class="widget-title">
                      <h3>Trending Now</h3>
                  </div>
                  <div class="widget-body">

                  </div>
              </div>-->
              <!-- End Trending Post -->
              <!-- Latest Post -->
              {% if servd %}
              <div class="widget widget-latest-post">
                  <div class="widget-title" style="background-color: #478ac9;">
                      <h3 style="color: white; font-family: 'Nunito', sans-serif;">Otros Servicios</h3>
                  </div>
                  <div class="widget-body">
                    {% for sd in servd %}
                      <div class="latest-post-aside media">
                          <div class="lpa-left media-body mb-2">
                              <div class="lpa-title">
                                  <h5 style="padding: 1rem 1rem 0 1rem; font-family: 'Nunito', sans-serif;"><a href="{% url 'home_app:service-detail' sd.pk %}" style="text-decoration: none;">{{ sd.title }}</a></h5>
                              </div>
                              <div style="width: 20%; border-bottom: 1px solid #478ac9" class="py-1"></div>
                              <!--<div class="lpa-meta">
                                  <a class="name" href="#">
                                      Rachel Roth
                                  </a>
                                  <a class="date" href="#">
                                      26 FEB 2020
                                  </a>
                              </div>-->
                          </div>
                          <div class="lpa-right m-0" style="width: 100%; padding: 1rem;">
                              <a href="{% url 'home_app:service-detail' sd.pk %}">
                                  <img src="{{ sd.image.url }}" title="{{ sd.title }}" alt="{{ sd.title }}" style="width: 100%; height: 10rem; object-fit: cover; border-radius: 15px;">
                              </a>
                          </div>
                      </div>
                    {% endfor %}
                  </div>
              </div>
              {% endif %}
              <!-- End Latest Post -->
              <!-- widget Tags -->
              {% if cate %}
              <div class="widget widget-tags">
                  <div class="widget-title">
                      <h3>Categorias</h3>
                  </div>
                  <div class="widget-body">
                      <div class="nav tag-cloud">
                        {% for c in cate%}
                          <a href="/servicios?categoria={{ c.name }}">{{ c.name }}</a>
                        {% endfor %}
                      </div>
                  </div>
              </div>
              {% endif %}
              <!-- End widget Tags -->
          </div>
      </div>
  </div>
</div>
{% endif %}
{% include 'includes/footer.html' %}
{% endblock content %}

clinica/templates/empresa/detailTecnologias.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Contacto {% endblock title %}
{% block css %}<link rel="stylesheet" href="{% static 'css/CLINICA.css' %}" media="screen"> {% endblock css %}
{% block content %}
{% include 'includes/header.html' %}
{% if object %}
<div class="blog-single gray-bg" style="background-image: linear-gradient(rgb(206, 223, 245), rgb(230, 236, 245), #f2f2f2); height: 80%;">
  <div class="container">
      <div class="row align-items-start">
          <div class="col-lg-8 m-15px-tb">
              <article class="article">
                  <div class="article-img" style="height: 20rem;">
                      <img src="{{ object.image.url }}" title="{{ object.title }}" alt="{{ object.title}}" style="object-fit: cover; width: 100%; height: 100%; border-radius: 15px;">
                  </div>
                  <div class="article-title">
                      <!--<h6><a href="#">Lifestyle</a></h6>-->
                      <h2 style="font-family: 'Nunito', sans-serif; margin-bottom: 0;">{{ object.title }}</h2>
                      <!--<div class="media">
                          <div class="avatar">
                              <img src="https://bootdey.com/img/Content/avatar/avatar1.png" title="" alt="">
                          </div>
                          <div class="media-body">
                              <label>Rachel Roth</label>
                              <span>26 FEB 2020</span>
                          </div>
                      </div>-->
                  </div>
                  <div class="article-content">
                      {{ object.description|safe }}
                  </div>
                  <!--<div class="nav tag-cloud">
                      <a href="#">Design</a>
                      <a href="#">Development</a>
                      <a href="#">Travel</a>
                      <a href="#">Web Design</a>
                      <a href="#">Marketing</a>
                      <a href="#">Research</a>
                      <a href="#">Managment</a>
                  </div>-->
              </article>
              <!--<div class="contact-form article-comment">
                  <h4>Leave a Reply</h4>
                  <form id="contact-form" method="POST">
                      <div class="row">
                          <div class="col-md-6">
                              <div class="form-group">
                                  <input name="Name" id="name" placeholder="Name *" class="form-control" type="text">
                              </div>
                          </div>
                          <div class="col-md-6">
                              <div class="form-group">
                                  <input name="Email" id="email" placeholder="Email *" class="form-control" type="email">
                              </div>
                          </div>
                          <div class="col-md-12">
                              <div class="form-group">
                                  <textarea name="message" id="message" placeholder="Your message *" rows="4" class="form-control"></textarea>
                              </div>
                          </div>
                          <div class="col-md-12">
                              <div class="send">
                                  <button class="px-btn theme"><span>Submit</span> <i class="arrow"></i></button>
                              </div>
                          </div>
                      </div>
                  </form>
              </div>-->
          </div>
          <div class="col-lg-4 m-15px-tb blog-aside">
              <!-- Author 
              <div class="widget widget-author">
                  <div class="widget-title">
                      <h3>Author</h3>
                  </div>
                  <div class="widget-body">
                      <div class="media align-items-center">
                          <div class="avatar">
                              <img src="https://bootdey.com/img/Content/avatar/avatar6.png" title="" alt="">
                          </div>
                          <div class="media-body">
                              <h6>Hello, I'm<br> Rachel Roth</h6>
                          </div>
                      </div>
                      <p>I design and develop services for customers of all sizes, specializing in creating stylish, modern websites, web services and online stores</p>
                  </div>
              </div>
              End Author -->
              <!-- Trending Post -->
              <!--<div class="widget widget-post">
                  <div class="widget-title">
                      <h3>Trending Now</h3>
                  </div>
                  <div class="widget-body">

                  </div>
              </div>-->
              <!-- End Trending Post -->
              <!-- Latest Post -->
              {% if tecnod %}
              <div class="widget widget-latest-post">
                  <div class="widget-title" style="background-color: #478ac9;">
                      <h3 style="color: white; font-family: 'Nunito', sans-serif;">Otras tecnologías</h3>
                  </div>
                  <div class="widget-body">
                    {% for td in tecnod %}
                      <div class="latest-post-aside media">
                          <div class="lpa-left media-body mb-2">
                              <div class="lpa-title">
                                  <h5 style="font-size: 1.1rem; padding: 1rem 1rem 0 1rem; font-family: 'Nunito', sans-serif;"><a href="{% url 'home_app:tecnologias-detail' td.pk %}" style="text-decoration: none;">{{ td.title }}</a></h5>
                              </div>
                              <div style="width: 20%; border-bottom: 1px solid #478ac9" class="py-1"></div>
                              <!--<div class="lpa-meta">
                                  <a class="name" href="#">
                                      Rachel Roth
                                  </a>
                                  <a class="date" href="#">
                                      26 FEB 2020
                                  </a>
                              </div>-->
                          </div>
                          <div class="lpa-right m-0" style="width: 100%; padding: 1rem;">
                              <a href="{% url 'home_app:tecnologias-detail' td.pk %}">
                                  <img src="{{ td.image.url }}" title="{{ td.title }}" alt="{{ td.title }}" style="width: 100%; height: 10rem; object-fit: cover; border-radius: 15px;">
                              </a>
                          </div>
                      </div>
                    {% endfor %}
                  </div>
              </div>
              {% endif %}
              <!-- End Latest Post -->
              <!-- widget Tags -->
              {% if cate %}
              <div class="widget widget-tags">
                  <div class="widget-title">
                      <h3>Categorias</h3>
                  </div>
                  <div class="widget-body">
                      <div class="nav tag-cloud">
                        {% for c in cate%}
                          <a href="/servicios?categoria={{ c.name }}">{{ c.name }}</a>
                        {% endfor %}
                      </div>
                  </div>
              </div>
              {% endif %}
              <!-- End widget Tags -->
          </div>
      </div>
  </div>
</div>
{% endif %}

{% include 'includes/footer.html' %}
{% endblock content %}