clinica/applications/home/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'home_app'

urlpatterns = [
    path(
        '', 
        views.InicioView.as_view(), 
        name='inicio'
    ),
    path(
        'contacto-form', 
        views.FormularioCreateView.as_view(), 
        name='contacto'
    ),
    path(
        'Horario-ubicacion', 
        views.HorariosUbicacionView.as_view(), 
        name='horarioUbicacion'
    ),
    path(
        'clínica', 
        views.ClinicaView.as_view(), 
        name='clinica'
    ),
    path(
        'Antes-Despues', 
        views.AntesDespues.as_view(), 
        name='antesdespues'
    ),
    path(
        'dtecnologias/<pk>/', 
        views.TecnosDetailView.as_view(), 
        name='tecnologias-detail'
    ),
    path(
        'tecnologias', 
        views.TecnosListView.as_view(), 
        name='tecnos-list'
    ),
    path(
        'dservicios/<pk>/', 
        views.ServiceDetailView.as_view(), 
        name='service-detail'
    ),
    path(
        'servicios', 
        views.ServListView.as_view(), 
        name='servicios-list'
    ),
]

clinica/clinica/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
#from applications.home.models import datos
from django.conf.urls import handler404, handler500
from applications.home.views import Error404view, Error405view


urlpatterns = [
    path('admin/', admin.site.urls, {'extra_context': {'mycontext': ''}}),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('applications.home.urls')),
    path('', include('applications.empresa.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = Error404view.as_view()
handler500 = Error405view.as_view()

clinica/applications/empresa/models.py
# -*- coding: utf-8 -*-
from datetime import datetime
from time import strftime
from django.db import models
from model_utils.models import TimeStampedModel
from ckeditor_uploader.fields import RichTextUploadingField
from .validators import phone_validation, house_validation
from ..home.managers import servicioManager
from applications.complementos.models import Tag, Redes, Especialidad, Categoria
from django.contrib.auth.models import AbstractBaseUser
from PIL import Image
import imagehash
import os

# Create your models here.

def wrapper(instance, filename):
        ext = filename.split('.')[-1]
        hash = imagehash.average_hash(Image.open(instance.image)).__str__()
        
        if hash:
            #Creando nuevo nombre
            filename = '{}.{}'.format(hash, ext) # do instance.username 

        return os.path.join('Tecnologias', filename)

def wrapper2(instance, filename):
        ext = filename.split('.')[-1]
        hash = imagehash.average_hash(Image.open(instance.image)).__str__()
        
        if hash:
            #Creando nuevo nombre
            filename = '{}.{}'.format(hash, ext) # do instance.username 

        return os.path.join('Servicios', filename)

def wrapper3(instance, filename):
        ext = filename.split('.')[-1]
        hash = imagehash.average_hash(Image.open(instance.image)).__str__()
        
        if hash:
            #Creando nuevo nombre
            filename = '{}.{}'.format(hash, ext) # do instance.username 

        return os.path.join('Empleados', filename)

# Informacion

class Informacion(models.Model):
    address = models.CharField('Direccion', max_length=60)
    district = models.CharField('Distrito', max_length=200)
    phome = models.CharField('Numero', validators=[phone_validation], max_length=9, unique=True)
    house = models.CharField('Numero Fijo', validators=[house_validation], max_length=10, unique=True)
    gmail = models.EmailField('Correo')
    redes = models.ManyToManyField(Redes)

    class Meta:
        verbose_name = 'Información'
        verbose_name_plural = 'Información'

    def __str__(self):
        return self.address

# ============================ 

# Tecnologia

class Tecnologia(models.Model):
    title = models.CharField('Nombre', max_length=30, unique=True)
    description = RichTextUploadingField('Descripción')
    image = models.ImageField('Imágen', upload_to=wrapper, blank=False, null=False, default='')
    hash = models.CharField(max_length=20, editable=False)
    public = models.BooleanField('Visible', default=False)

    class Meta:
        verbose_name = 'Tecnologia'
        verbose_name_plural = 'Tecnologias'
        
    def __str__(self):
        return self.title

# ==================================== 

# Horarios y ubicacion

class Horario(models.Model):

    horarios= (
        ('0', 'Lunes'),
        ('1', 'Martes'),
        ('2', 'Miercoles'),
        ('3', 'Jueves'),
        ('4', 'Viernes'),
        ('5', 'Sábado'),
        ('6', 'Domingo'),
    )
    the = models.CharField('De', max_length=11, choices=horarios)
    to = models.CharField('a', max_length=11, choices=horarios, blank=True)
    of = models.TimeField('Desde')
    until = models.TimeField('Hasta')
    public = models.BooleanField('Visible', default=False)

    class Meta:
        verbose_name = 'Horario'
        verbose_name_plural = 'Horarios'

    def __str__(self):
        day = " "
        day2 = " "
        inicio = " "
        final = " "
        for c in self.the:
            if c == '0':
                day = 'Lunes'
            if c == '1':
                day = 'Martes'
            if c == '2':
                day = 'Miercoles'
            if c == '3':
                day = 'Jueves'
            if c == '4':
                day = 'Viernes'
            if c == '5':
                day = 'Sábado'
            if c == '6':
                day = 'Domingo'    
            for d in self.to:
                if d == '0':
                    day2 = 'Lunes'
                if d == '1':
                    day2 = 'Martes'
                if d == '2':
                    day2 = 'Miercoles'
                if d == '3':
                    day2 = 'Jueves'
                if d == '4':
                    day2 = 'Viernes'
                if d == '5':
                    day2 = 'Sábado'
                if d == '6':
                    day2 = 'Domingo'

        a = self.of.strftime("%H:%M")
        b = self.until.strftime("%H:%M")

        if self.of.hour >= 12 and self.of.hour <=24:
            inicio =  a + ' pm'
        else:
            inicio = a + ' am'
        
        if self.until.hour >= 12 and self.until.hour <=24:
            final =  b + ' pm'
        else:
            final = b + ' am'
        
        if day2 == " ":
            return day + ' / ' + 'Desde ' + inicio + ' hasta ' + final
        else:
            return 'De' + ' ' + day + ' a ' + day2 + ' / ' + 'Desde ' + inicio + ' hasta ' + final

# ====================================

# Servicios

class Servicio(TimeStampedModel):
    title = models.CharField('Nombre', max_length=20, unique=True)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE, related_name='s_cate')
    image = models.ImageField('Imagen', upload_to=wrapper2, blank=False, null=False, default='')
    description = RichTextUploadingField('Contenido')
    etiquetas = models.ManyToManyField(Tag)
    public  = models.BooleanField('Visible', default=False)
    slug = models.SlugField(editable=False, max_length=300)

    objects = servicioManager()

    class Meta:
        verbose_name = 'Servicio'
        verbose_name_plural = 'Servicios'
    
    def __str__(self):
        return self.title

# ====================================

#Configuracion 

class Configuration(models.Model):
    tls = models.BooleanField('EMAIL_USE_TLS',default=True, blank=False)
    emailhost = models.CharField('EMAIL_HOST',max_length=1024, default = "smtp.gmail.com", blank=False)
    email = models.EmailField('EMAIL_USER', max_length=255, blank = False)
    password = models.CharField('EMAIL_PASS', max_length=255, blank = False)
    emailport = models.PositiveSmallIntegerField('EMAIL_PORT',default=587, blank=False)

    class Meta:
        verbose_name = 'Configuración'
        verbose_name_plural = 'Configuración'


# Empleado
 
class Empleado(TimeStampedModel):
    name = models.CharField('Nombre', max_length=30)
    last_name = models.CharField('Apellido', max_length=30)
    image = models.ImageField('Foto Perfil', upload_to=wrapper3, blank=False, null=False)
    especialidad = models.ManyToManyField(Especialidad)
    cop = models.CharField('C.O.P', max_length=10)
    public = models.BooleanField('Pestaña Clinica', default=False)
    inicio = models.BooleanField('Pestaña Inicio', default=False)
    
    class Meta:
        verbose_name = 'Empleado'
        verbose_name_plural = 'Empleados'
        ordering = ['name']
        unique_together = ('name', 'last_name')

    def __str__(self):
        return self.name + ' ' + self.last_name

# ==================================== 

clinica/applications/home/models.py
from tabnanny import filename_only
from django.db import models
from applications.empresa.models import Tecnologia, Horario, Servicio, Empleado
from applications.complementos.models import Instalaciones
from applications.clientes.models import Sonrisa 
from PIL import Image
import imagehash
import os

# Create your models here.

#INICIO
class PInicio(models.Model):

    def wrapper(instance, filename):
        ext = filename.split('.')[-1]
        hash = imagehash.average_hash(Image.open(instance.logo)).__str__()
        
        if hash:
            #Creando nuevo nombre
            filename = '{}.{}'.format(hash, ext) # do instance.username 

        return os.path.join('Home', filename)

    title = models.CharField('Titulo', max_length=50, unique=True)
    sub_title = models.CharField('Frase', max_length=50)
    image = models.ImageField('Imágen', upload_to=wrapper, blank=False, null=False)
    logo = models.ImageField('Logo', upload_to=wrapper, blank=False, null=False)
    bdescription = models.TextField('Descripción Breve', max_length=150)
    Mision = models.TextField('Misión', max_length=200, blank=True, null=True)
    vision = models.TextField('Visión', max_length=200, blank=True, null=True)
    empleados = models.ManyToManyField(Empleado, blank=True)
    servicios = models.ManyToManyField(Servicio, blank=True)
    comentarios = models.ManyToManyField(Sonrisa, blank=True)
    
    class Meta:
        verbose_name = 'P. Inicio'
        verbose_name_plural = 'P. Inicio'
        
    def __str__(self):
        return self.title

# Clinica 

class Pclinica(models.Model):
    #Cambiando nombre de imagen

    def wrapper(instance, filename):
        ext = filename.split('.')[-1]
        hash = imagehash.average_hash(Image.open(instance.image)).__str__()
        
        if hash:
            #Creando nuevo nombre
            filename = '{}.{}'.format(hash, ext) # do instance.username 

        return os.path.join('Home', filename)
        
    title = models.CharField('Titulo', max_length=50, unique=True)
    image = models.ImageField('Imágen', upload_to=wrapper, blank=False, null=False)
    description = models.TextField('Descripción extensa', max_length=500)
    instalaciones = models.ManyToManyField(Instalaciones, blank=True)
    empleados = models.ManyToManyField(Empleado, blank=True)
    public = models.BooleanField('Visible', default=False)
    

    class Meta:
        verbose_name = 'P. Clinica'
        verbose_name_plural = 'P. Clinica'
        
    def __str__(self):
        return self.title
    
    
# ==================================== 

#Servicios

class Pservicio(models.Model):
    servicios= models.ManyToManyField(Servicio, blank=True)
    public = models.BooleanField('Visible', default=False)

    class Meta:
        verbose_name = 'P. Servicios'
        verbose_name_plural = 'P. Servicios'
        
    def __str__(self):
        return "Servicio"

#=====================================

# Tecnologias

class Ptecnologias(models.Model):
    tecnologias = models.ManyToManyField(Tecnologia, blank=True)
    public = models.BooleanField('Visible', default=False)

    class Meta:
        verbose_name = 'P.Tecnologías'
        verbose_name_plural = 'P. Tecnologías'

    def __str__(self):
        return "Tecnologias"

#=====================================

# Antes y Despues

class PantesDespues(models.Model):
    sonrisas = models.ManyToManyField(Sonrisa, blank=True)
    public = models.BooleanField('Visible', default=False)
    
    class Meta:
        verbose_name = 'P. Antes y Después'
        verbose_name_plural = 'P. Antes y Después'

    def __str__(self):
        return "Antes y después"

#=====================================

#Contacto

class Pcontanto(models.Model):
    wsp = models.BooleanField('whatsApp', default=False)
    email = models.BooleanField('Correo', default=False)

    class Meta:
        verbose_name = 'P. Contanto'
        verbose_name_plural = 'P. Contacto'

    def __str__(self):
        return "¿Dónde desea recibir mensajes?"
        
# Horario Ubicacion

class PhorarioUbicacion(models.Model):
    horarios = models.ManyToManyField(Horario, blank=True)
    public = models.BooleanField('Horarios Visible', default=False)
    info = models.BooleanField('Ubicación Visible', default=False)

    class Meta:
        verbose_name = 'P. Horario y Ubicación'
        verbose_name_plural = 'P. Horarios y Ubicación'

    def __str__(self):
        return "Horarios y Ubicacion"
#=====================================

def datos():
    c = Pclinica.objects.exists()
    if c:
        c = Pclinica.objects.first()
    else:
        c = "none"
    return c

clinica/applications/home/forms.py
from django import forms

from applications.clientes.models import Formulario

class FormularioForm(forms.ModelForm):
    class Meta:
        model = Formulario
        fields = {
            'name',
            'email',
            'phone',
            'message',
        }
    
        widgets ={
            'name': forms.TextInput(attrs={'class': 'u-grey-10 u-input u-input-rectangle form-control', 'placeholder': 'Ingrese nombre completo', 'id': 'valiname'}),
            'email': forms.EmailInput(attrs={'class': 'u-grey-10 u-input u-input-rectangle form-control', 'placeholder': 'Ingrese correo', 'id': 'valiemail'}),
            'phone': forms.TextInput(attrs={'class': 'u-grey-10 u-input u-input-rectangle form-control bg-gradient-info', 'placeholder': 'Ingrese numero de celular', 'id': 'validationServerUsername'}),
            'message': forms.Textarea(attrs={'class': 'u-grey-10 u-input u-input-rectangle form-control', 'placeholder': 'Ingrese mensaje', 'id': 'valimessage'})
        }


        

clinica/templates/home/Horarios.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Horarios y Ubicación {% endblock title %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/Horarios.css' %}" media="screen">
{% endblock css %}
{% block content %}
{% include 'includes/header.html' %}

<section class="u-align-center u-clearfix u-block-b2ac-1" custom-posts-hash="[]"
  data-section-properties="{&quot;margin&quot;:&quot;none&quot;,&quot;stretch&quot;:true}" data-id="b2ac"
  data-posts-content="[]" style="background-image: linear-gradient(rgb(206, 223, 245), rgb(230, 236, 245), #f2f2f2);" data-style="table-3new" id="sec-77de" data-source="Sketch">
  {% if horario == 'noe' %}
  <script>
    Swal.fire({
      background: "#fff",
      title: "<strong>HORARIO/UBICACIÓN</strong> <br> <h3 style='color: rgb(255,105,97)'>NO EXISTE</h3>",
      html: "En el administrador dirígase a <br><strong style='color: #3085d6'>Pestañas &#10142; P.Horario y Ubicación </strong> <br> y cree uno",
      icon: 'error',
      confirmButtonColor: '#3085d6',
      confirmButtonText: 'ok',
    })
  </script>
  {% else %}
  {% if not horario.public and not horario.info %}
  <script>
    Swal.fire({
      background: "#fff",
      title: "<strong>No visible</strong>",
      html: "En el administrador dirígase a <br><strong style='color: #3085d6'>Pestañas &#10142; P. Horario y Ubicación</strong><br> para activarlo",
      icon: 'warning',
      confirmButtonColor: '#3085d6',
      confirmButtonText: 'ok',
    })
  </script>
  {% else %}
  {% if horario.public %}
  <div class="u-clearfix u-sheet u-valign-middle u-block-b2ac-2" style="min-height: 200px">
    <div class="u-expanded-width u-table u-table-responsive u-block-control u-block-b2ac-40"
      style="margin-top: 42px; margin-right: auto; margin-bottom: 42px; margin-left: 0" data-block="83"
      data-block-type="Table">
      <table class="u-table-entity u-block-b2ac-3" style="">
        <colgroup>


          <col width="49.9%">
          <col width="50.1%">
        </colgroup>
        <thead class="u-black u-table-header u-block-b2ac-4" style="font-weight: 700; background-image: none">

          <tr style="height: 30.7px;">
            <th class="u-table-cell u-block-control u-palette-1-base u-block-b2ac-12" style="background-image: none;"
              data-block="90" data-block-type="TableCell">Dias </th>
            <th class="u-table-cell u-block-control u-palette-1-base u-block-b2ac-34" style="background-image: none;"
              data-block="91" data-block-type="TableCell">Hora </th>
          </tr>
        </thead>
        <tbody class="u-table-alt-palette-1-light-3 u-table-body u-block-b2ac-9" style="">
          {% for h in horario.horarios.all %}

          <tr style="height: 65px;">


            <td class="u-table-cell u-block-control u-block-b2ac-26" style="font-family: 'Nunito', sans-serif;" data-block="98"
              data-block-type="TableCell">{% if not h.get_to_display %} {{ h.get_the_display }} {% else %} {{ h.get_the_display }} a {{ h.get_to_display }} {% endif %}</td>
            <td class="u-table-cell u-block-control u-block-b2ac-31" style="font-family: 'Nunito', sans-serif;" data-block="99"
              data-block-type="TableCell">De {% if h.of.hour >= 12 and h.of.hour <= 24 %}{{ h.of }} pm {% else %} {{ h.of }} am {% endif %} a {% if h.until.hour >= 12 and h.until.hour <= 24 %}{{ h.until }} pm {% else %} {{ h.until }} am {% endif %}</td>
          </tr>
          {% endfor %}
        </tbody>
        <tfoot class="hidden u-table-footer u-block-b2ac-35" style="">
          <tr class="hidden u-block-b2ac-50" style="">


            <td class="u-table-cell u-block-control u-block-b2ac-53" style="" data-block="110"></td>
            <td class="u-table-cell u-block-control u-block-b2ac-54" style="" data-block="111"></td>
          </tr>
        </tfoot>
      </table>
    </div>
  </div>
  <style data-mode="XL">
    @media (max-width: 0px) {
      .u-block-b2ac-2 {
        min-height: 464px
      }

      .u-block-b2ac-40 {
        margin-top: 42px;
        margin-right: auto;
        margin-bottom: 42px;
        margin-left: 0
      }

      .u-block-b2ac-4 {
        font-weight: 700;
        background-image: none
      }

      .u-block-b2ac-12 {
        background-image: none
      }

      .u-block-b2ac-34 {
        background-image: none
      }
    }
  </style>
  <style data-mode="LG">
    @media (max-width: 0px) {
      .u-block-b2ac-2 {
        min-height: 464px
      }

      .u-block-b2ac-40 {
        margin-top: 42px;
        margin-bottom: 42px
      }

      .u-block-b2ac-3 {
        min-height: 100px
      }

      .u-block-b2ac-4 {
        font-weight: 700;
        background-image: none
      }

      .u-block-b2ac-12 {
        background-image: none
      }

      .u-block-b2ac-34 {
        background-image: none
      }
    }
  </style>
  <style data-mode="MD">
    @media (max-width: 0px) {
      .u-block-b2ac-2 {
        min-height: 464px
      }

      .u-block-b2ac-40 {
        margin-top: 42px;
        margin-bottom: 42px
      }

      .u-block-b2ac-3 {
        min-height: 100px
      }

      .u-block-b2ac-4 {
        font-weight: 700;
        background-image: none
      }

      .u-block-b2ac-12 {
        background-image: none
      }

      .u-block-b2ac-34 {
        background-image: none
      }
    }
  </style>
  <style data-mode="SM">
    @media (max-width: 0px) {
      .u-block-b2ac-2 {
        min-height: 464px
      }

      .u-block-b2ac-40 {
        margin-top: 42px;
        margin-bottom: 42px
      }

      .u-block-b2ac-3 {
        min-height: 100px
      }

      .u-block-b2ac-4 {
        font-weight: 700;
        background-image: none
      }

      .u-block-b2ac-12 {
        background-image: none
      }

      .u-block-b2ac-34 {
        background-image: none
      }
    }
  </style>
  <style data-mode="XS">
    @media (max-width: 0px) {
      .u-block-b2ac-2 {
        min-height: 464px
      }

      .u-block-b2ac-40 {
        margin-top: 42px;
        margin-bottom: 42px
      }

      .u-block-b2ac-3 {
        min-height: 100px
      }

      .u-block-b2ac-4 {
        font-weight: 700;
        background-image: none
      }

      .u-block-b2ac-12 {
        background-image: none
      }

      .u-block-b2ac-34 {
        background-image: none
      }
    }
  </style>
  {% endif %}
  {% if horario.info %}
  <div class="u-clearfix u-gradient u-section-2" id="sec-11ff">
    <div class="u-clearfix u-sheet u-valign-middle u-sheet-1">
      <div class="u-clearfix u-expanded-width u-layout-wrap u-layout-wrap-1">
        <div class="u-layout">
          <div class="u-layout-row">
            <div class="u-align-left u-container-style u-layout-cell u-left-cell u-size-30 u-layout-cell-1">
              <div class="u-container-layout u-valign-middle u-container-layout-1">
                <h2 class="u-custom-font u-font-oswald u-text u-text-palette-1-base u-text-1"
                  data-animation-name="fadeIn" data-animation-duration="1000" data-animation-delay="0"
                  data-animation-direction="Down" style="font-family: 'Nunito', sans-serif;">{{ clinica.title }}</h2>
                <p class="u-text u-text-palette-5-dark-2 u-text-2" data-animation-name="fadeIn"
                  data-animation-duration="1000" data-animation-delay="250" data-animation-direction="Down" style="font-family: 'Nunito', sans-serif;">{{ info.address }} {{ info.district }} | Lima - Peru</p>
                <p class="u-text u-text-palette-5-dark-2 u-text-3" data-animation-name="fadeIn"
                  data-animation-duration="1000" data-animation-delay="250" data-animation-direction="Down" style="font-family: 'Nunito', sans-serif;">{{ info.gmail }}</p>
                <p class="u-text u-text-palette-5-dark-2 u-text-4" data-animation-name="fadeIn"
                  data-animation-duration="1000" data-animation-delay="250" data-animation-direction="Down" style="font-family: 'Nunito', sans-serif;">
                  <a
                    href="https://api.whatsapp.com/send?phone=51{{info.phome}}&text=Bienvenid@, en que podemos ayudarte? :)">+51
                    {{ info.phome }}</a>
                </p>
              </div>
            </div>
            <div class="u-container-style u-layout-cell u-right-cell u-size-30 u-layout-cell-2">
              <div class="u-container-layout u-container-layout-2">
                <div class="u-expanded u-grey-10 u-map">
                  <div class="embed-responsive">
                    {% if info %}
                    <iframe width="600" height="450" style="border:0; padding: 4px 4px 4px 4px;" loading="lazy"
                      allowfullscreen referrerpolicy="no-referrer-when-downgrade" src="https://www.google.com/maps/embed/v1/place?key=AIzaSyAZeliFZqV-EM0HSy5AlO6D-k8IpwoUHd4
                              &q={{ info.address }},{{ info.district }}">
                    </iframe>
                    {% endif %}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endif %}
  {% endif %}
  {% endif %}
</section>

{% include 'includes/footer.html' %}
{% endblock content %}

clinica/templates/home/error_505.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Error 505</h1>
</body>
</html>